theme: jekyll-theme-cayman
title: "Workshop: Towards Designing Visualisations for the Emergent Users of ICTs"
description: "India HCI '20, Online, India, November 6 - 8, 2020"
github:
  is_project_page: false
