theme: jekyll-theme-cayman
title: "Towards Designing Visualisations for the Emergent Users of ICTs"
description: "India HCI '20, Online, India, November 5, 9 AM to 12 Noon IST (UTC+5:30)"
github:
  is_project_page: false
